### ISSUE TITLE
Warning/welcome message sometimes fails to appear after joining

### ISSUE THREAD

**Issue by jlillis** [Sparker95/TaskForceEnforcer#2]
In some missions, the warning/welcome message that tell the player to join the TS server fails to appear when joining the mission. I believe this has to do with the mission interacting with a titleText after TaskForceEnforcer displays the message.

Tested on a server running the Domination mission (https://github.com/Xeno69/Domination).

**Comment by Sparker95** [comment]
Hi, thanks for the interest in this project I did a long time ago. I am sorry but I don't have time to repair this right now.

I think that your guess is most likely right. If I were to rewrite this today, I'd add some on-screen message of another kind, most likely some black control on main display covering whole screen, with text in the middle. It should be fairly easy to do. If you want I can try to help you code this, but all testing and so on will be on your side.
